from pathlib import Path, PurePath, PurePosixPath

# project hierarchy
PROJECT_NAME = "lfvddp"
LOCAL_PROJECT_ROOT = Path(__file__).parent.parent.absolute()
CONFIGS_DIR = LOCAL_PROJECT_ROOT / "configs"
TRAIN_DIR = LOCAL_PROJECT_ROOT / "train"
PLOT_DIR = LOCAL_PROJECT_ROOT / "plot"
SINGULARITY_DEFINITION_FILE = LOCAL_PROJECT_ROOT / f"{PROJECT_NAME}.def"

def get_relpath_from_local_root(local_absolute_path: PurePath) -> PurePosixPath:
    return PurePosixPath(local_absolute_path.relative_to(LOCAL_PROJECT_ROOT))


# At containsr
CONTAINER_PROJECT_ROOT = PurePosixPath("/app")

def path_as_in_container(local_path: Path) -> PurePosixPath:
    relative_path = get_relpath_from_local_root(local_path)
    return CONTAINER_PROJECT_ROOT / relative_path


# Entrypoint scripts
SINGLE_TRAIN_SCRIPT_NAME = "single_train.py"
SUBMIT_TRAIN_SCRIPT_NAME = "submit_train.py"
CREATE_PLOTS_SCRIPT_NAME = "create_plots.py"

SINGLE_TRAIN_SCRIPT = TRAIN_DIR / SINGLE_TRAIN_SCRIPT_NAME
SUBMIT_TRAIN_SCRIPT = TRAIN_DIR / SUBMIT_TRAIN_SCRIPT_NAME
CREATE_PLOTS_SCRIPT = PLOT_DIR / CREATE_PLOTS_SCRIPT_NAME

SINGLE_TRAIN_SCRIPT_RELATIVE = get_relpath_from_local_root(SINGLE_TRAIN_SCRIPT)
SUBMIT_TRAIN_SCRIPT_RELATIVE = get_relpath_from_local_root(SUBMIT_TRAIN_SCRIPT)
CREATE_PLOTS_SCRIPT_RELATIVE = get_relpath_from_local_root(CREATE_PLOTS_SCRIPT)

CONTAINER_SINGLE_TRAIN_PATH = path_as_in_container(SINGLE_TRAIN_SCRIPT)
CONTAINER_CREATE_PLOTS_PATH = path_as_in_container(CREATE_PLOTS_SCRIPT)


# File extensions
## Textual data
JSON_FILE_EXTENSION = "json"
YAML_FILE_EXTENSION = "yaml"
YML_FILE_EXTENSION = "yml"
YAML_FILE_EXTENSIONS = [YAML_FILE_EXTENSION, YML_FILE_EXTENSION]
CONFIG_FILE_EXTENSIONS = [JSON_FILE_EXTENSION, *YAML_FILE_EXTENSIONS]
TEXT_FILE_EXTENSION = "txt"
BASH_FILE_EXTENSION = "sh"
## Training logs
TRAINING_LOG_FILE_EXTENSION = "h5"
TRAINING_HISTORY_LOG_FILE_SUFFIX = "history." + TRAINING_LOG_FILE_EXTENSION
TRAINING_WEIGHTS_LOG_FILE_SUFFIX = "weights." + TRAINING_LOG_FILE_EXTENSION
TRAINING_RESULT_FILE_EXTENSION = TEXT_FILE_EXTENSION
## Plotting
PLOT_FILE_EXTENSION = "png"

# File title constants
CONTEXT_FILE_NAME = f"context.{JSON_FILE_EXTENSION}"
JOB_OUTPUT_FILE_NAME = f"job_output.{TEXT_FILE_EXTENSION}"
RESULTS_BRIEFING_FILE_NAME = f"results_briefing.{TEXT_FILE_EXTENSION}"

# NN training
TRAINING_OUTCOMES_DIR_NAME = "training_outcomes"
TRAINING_CHECKPOINT_SUFFIX = "checkpoint.pt"
CHECKPOINTS_DIR_NAME = "checkpoints"
SINGLE_TRAIN_T_FILE_NAME = f"single_t.{TRAINING_RESULT_FILE_EXTENSION}"
RESULTING_T_FILE_STEM = f"final_t"
RESULTING_T_FILE_NAME = f"{RESULTING_T_FILE_STEM}.{TRAINING_RESULT_FILE_EXTENSION}"
WEIGHTS_OUTPUT_FILE_NAME = f"training_result.{TRAINING_WEIGHTS_LOG_FILE_SUFFIX}"
TENSORBOARD_LOG_DIR_NAME = f"tensorboard_logs"
